name: picozoa
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - trim-galore=0.6.1
  - multiqc=1.7
  - spades=3.13.0
  - quast=5.0.2
  - prodigal=2.6.3
  - barrnap=0.9
